  - name: Playbook
    hosts: all
    remote_user: centos
    become: 'yes'
    become_user: root

    tasks:
      - name: Install Dependencies
        yum:
          name: epel-release
          state: latest

      - name: Install FTP Server
        yum:
          name: proftpd
          state: latest

      - name: Start FTP Server
        ansible.builtin.systemd:
          state: started
          name: proftpd

      - name: Enable FTP Server
        ansible.builtin.systemd:
          name: proftpd
          enabled: yes
      
      - name: Create a user with hashed password
        user:
          name: devsecops
          shell: /bin/bash
          password: it351mu


          